<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="DESKTOP-B7UDF6D" name="com.testng.properties.Demo_Transform" tests="10" failures="2" timestamp="2021-12-27T13:55:11 IST" time="0.416" errors="0">
  <testcase name="username" time="0.043" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="username" time="0.093" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="password" time="0.044" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="password" time="0.168" classname="com.testng.properties.Demo_Transform">
    <failure type="java.lang.AssertionError" message="expected [Ajith] but found [Ajith@]">
      <![CDATA[java.lang.AssertionError: expected [Ajith] but found [Ajith@]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.testng.properties.Demo_Transform.password(Demo_Transform.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="password" time="0.025" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="username" time="0.004" classname="com.testng.properties.Demo_Transform">
    <failure type="java.lang.AssertionError" message="expected [Aj2ith] but found [Ajith]">
      <![CDATA[java.lang.AssertionError: expected [Aj2ith] but found [Ajith]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.testng.properties.Demo_Transform.username(Demo_Transform.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="password" time="0.010" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="username" time="0.011" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
  <testcase name="password" time="0.003" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- password -->
  <system-out/>
  <testcase name="username" time="0.015" classname="com.testng.properties.Demo_Transform">
    <skipped/>
  </testcase> <!-- username -->
  <system-out/>
</testsuite> <!-- com.testng.properties.Demo_Transform -->
